name: Domain RUN
on:
  workflow_dispatch:
jobs:
  script:
    runs-on: ubuntu-latest
    container: ubuntu
  #   container:
  #     image: ghcr.io/mkorthof/freenom_script
  #  #   credentials:
  #  #     freenom_email: ${{  secrets.EMAIL }}
  #  #     freenom_passwd: ${{  secrets.PW }}
  #   steps:
  #       - name: test1
  #         run: ls
  #    #   - name: test2 
  #    #     run: freenom -l
  #       - name: test3 
  #         run: docker run --rm --env freenom_email=${{  secrets.EMAIL }} --env freenom_passwd=${{  secrets.PW }} ghcr.io/mkorthof/freenom-script -l
            
    steps:
      # - name: Pull and create 
      #   uses: actions/checkout@v3
      #   with:
      #     # Repository name with owner. For example, actions/checkout
      #     # Default: ${{ github.repository }}
      #     repository: mkorthof/freenom-script
      # - name: create      
      #   run: make docker
      # - name: Run the build process with Docker
      #   uses: addnab/docker-run-action@v3
      #   with:
      #       image: ghcr.io/mkorthof/freenom_script:latest
      #       options: --env freenom_email=${{  secrets.EMAIL }} --env freenom_passwd=${{  secrets.PW }} ghcr.io/mkorthof/freenom-script -l
      - name: show IP 
        run: curl icanhazip.com
      - name: RUN docker 
        run: |
          docker run -d \
          --name=webtop \
          --security-opt seccomp=unconfined `#optional` \
          -e PUID=1000 \
          -e PGID=1000 \
          -e TZ=Europe/London \
          -e SUBFOLDER=/ `#optional` \
          -e KEYBOARD=de-de-qwertz `#optional` \
          -e TITLE=Webtop `#optional` \
          -p 6969:3000 \
          -v /config:/config \
          --shm-size="1gb" `#optional` \
          --restart unless-stopped \
          lscr.io/linuxserver/webtop:latest
      - run: apt-get update; apt-get install curl -y
      - run: curl juice_shop_app:3000 > curl_result_docker
      - run: cat curl_result_docker
      - name: docker stats 
        run: docker stats
      - name: wait 
        run: sleep 120
      # - name: log
      #   run: cat /tmp/freenom.log