name: Domain RUN
on:
  workflow_dispatch:
jobs:
  script:
    runs-on: ubuntu-latest
  #   container:
  #     image: ghcr.io/mkorthof/freenom_script
  #  #   credentials:
  #  #     freenom_email: ${{  secrets.EMAIL }}
  #  #     freenom_passwd: ${{  secrets.PW }}
  #   steps:
  #       - name: test1
  #         run: ls
  #    #   - name: test2 
  #    #     run: freenom -l
  #       - name: test3 
  #         run: docker run --rm --env freenom_email=${{  secrets.EMAIL }} --env freenom_passwd=${{  secrets.PW }} ghcr.io/mkorthof/freenom-script -l
            
    steps:
      # - name: Pull and create 
      #   uses: actions/checkout@v3
      #   with:
      #     # Repository name with owner. For example, actions/checkout
      #     # Default: ${{ github.repository }}
      #     repository: mkorthof/freenom-script
      # - name: create      
      #   run: make docker
      # - name: Run the build process with Docker
      #   uses: addnab/docker-run-action@v3
      #   with:
      #       image: ghcr.io/mkorthof/freenom_script:latest
      #       options: --env freenom_email=${{  secrets.EMAIL }} --env freenom_passwd=${{  secrets.PW }} ghcr.io/mkorthof/freenom-script -l
      - name: show IP 
        run: curl icanhazip.com
      # - name: RUN docker 
      #   run: docker run --rm --env freenom_email=${{  secrets.EMAIL }} --env freenom_passwd=${{  secrets.PW }} freenom-script:latest -r -a

      # - name: log
      #   run: cat /tmp/freenom.log